[package]
name = "flexim-data-visualize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flexim-data-type.workspace = true
egui.workspace = true
egui_tiles.workspace = true