[package]
name = "polars"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
polars-core = { version = "0.35.4", default-features = false, features = [ "dtype-struct", "dtype-categorical", "strings", "regex", "serde" ] }
polars-io = { version = "0.35.4", optional = true, default-features = false, features = ["serde", "dtype-categorical", "dtype-struct"] }
polars-ops = { version = "0.35.4", default-features = false, features = [ "dtype-struct", "dtype-categorical", "strings", ] }

[features]
io = ["polars-io"]
ipc = ["polars-io/ipc"]
csv = ["polars-io/csv"]